[package]
name = "lattix-local"
version = "0.1.0"
edition = "2024"
description = "More beautiful puzzle solving"
authors = ["Sup#2.0"]
license = "MIT"
repository = "https://github.com/Sup2point0/lattix"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
