export const tips = [
  "Press <code>/</code> to view all keybinds.",
  "Hold <code>CTRL</code> while clicking on cells to select multiple at once.",
  "Hold <code>SHIFT</code> while clicking on a cell to highlight it.",
  "Hold <code>SHIFT</code> while typing a number to turn it into a mark.",
  "You can use arrow keys to navigate in the grid.",
  "Hold <code>ALT</code> while using arrow keys to jump to an edge of the grid.",
  "Press <code>M</code> to toggle mark-making.",
  "Press <code>P</code> to open the <span>Control Pane</span>.",
  "Not happy with how things look? You can customise it in the <span>Control Pane</span>.",
  "Grid getting too big? You can shrink the cell sizes in the <span>Control Pane</span>.",
  "Once you're on the home straight for a puzzle, you can disable mark-making to speed things up.",
  "Found a bug or issue? Drop an issue on lattix's GitHub.",
  "Got an idea for a feature? Drop a discussion on lattix's GitHub.",
  "You can find thousands of fantastic puzzles at <span>brainbashers.com</span>!",
  "For the love of puzzles!",
  "What puzzle will it be today?",
  "Puzzles are like sweets for the mind, except they're super healthy.",
  "If you like maths, and especially if you like integration, you should check out my website <span>Integrity</span>!",
  "This message is a puzzle!",
  "61, 52, 63, 94, 46, 18",
]
